// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wJAowqBqcWtGU49FNparet
// Component: sIES9jLTWq
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { ModeValue, useMode } from "./PlasmicGlobalVariant__Mode"; // plasmic-import: Lw3WceeDIP/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_disuko_website.module.css"; // plasmic-import: wJAowqBqcWtGU49FNparet/projectcss
import sty from "./PlasmicDarkMode.module.css"; // plasmic-import: sIES9jLTWq/css

export type PlasmicDarkMode__VariantMembers = {};
export type PlasmicDarkMode__VariantsArgs = {};
type VariantPropType = keyof PlasmicDarkMode__VariantsArgs;
export const PlasmicDarkMode__VariantProps = new Array<VariantPropType>();

export type PlasmicDarkMode__ArgsType = {};
type ArgPropType = keyof PlasmicDarkMode__ArgsType;
export const PlasmicDarkMode__ArgProps = new Array<ArgPropType>();

export type PlasmicDarkMode__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultDarkModeProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    await promise;
  });

function PlasmicDarkMode__RenderFunc(props: {
  variants: PlasmicDarkMode__VariantsArgs;
  args: PlasmicDarkMode__ArgsType;
  overrides: PlasmicDarkMode__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    mode: useMode()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.rootglobal_mode_lightMode]: hasVariant(
            globalVariants,
            "mode",
            "lightMode"
          )
        }
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDarkMode__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDarkMode__VariantsArgs;
    args?: PlasmicDarkMode__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicDarkMode__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicDarkMode__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicDarkMode__ArgProps,
          internalVariantPropNames: PlasmicDarkMode__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicDarkMode__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDarkMode";
  } else {
    func.displayName = `PlasmicDarkMode.${nodeName}`;
  }
  return func;
}

export const PlasmicDarkMode = Object.assign(
  // Top-level PlasmicDarkMode renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicDarkMode
    internalVariantProps: PlasmicDarkMode__VariantProps,
    internalArgProps: PlasmicDarkMode__ArgProps
  }
);

export default PlasmicDarkMode;
/* prettier-ignore-end */
