// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bsHvoheJaXyaeWhnCxRakT
// Component: FBEYeLCsKl6
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: _De9lHvhQM/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent
import MusicSlides from "../../MusicSlides"; // plasmic-import: 1BhlLFOXJu/component
import Footer from "../../Footer"; // plasmic-import: phAOjgqEmd/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_disuko_website_v_2.module.css"; // plasmic-import: bsHvoheJaXyaeWhnCxRakT/projectcss
import sty from "./PlasmicMusic.module.css"; // plasmic-import: FBEYeLCsKl6/css

export type PlasmicMusic__VariantMembers = {};
export type PlasmicMusic__VariantsArgs = {};
type VariantPropType = keyof PlasmicMusic__VariantsArgs;
export const PlasmicMusic__VariantProps = new Array<VariantPropType>();

export type PlasmicMusic__ArgsType = {};
type ArgPropType = keyof PlasmicMusic__ArgsType;
export const PlasmicMusic__ArgProps = new Array<ArgPropType>();

export type PlasmicMusic__OverridesType = {
  root?: p.Flex<"div">;
  navbar?: p.Flex<typeof Navbar>;
  main?: p.Flex<"div">;
  reveal?: p.Flex<typeof Reveal>;
  freeBox?: p.Flex<"div">;
  musicSlides?: p.Flex<typeof MusicSlides>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultMusicProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    await promise;
  });

function PlasmicMusic__RenderFunc(props: {
  variants: PlasmicMusic__VariantsArgs;
  args: PlasmicMusic__ArgsType;
  overrides: PlasmicMusic__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicMusic.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicMusic.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicMusic.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <div
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              projectcss.plasmic_tokens,
              sty.root
            )}
          >
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <p.Stack
              as={"div"}
              data-plasmic-name={"main"}
              data-plasmic-override={overrides.main}
              hasGap={true}
              className={classNames(projectcss.all, sty.main)}
            >
              <Reveal
                data-plasmic-name={"reveal"}
                data-plasmic-override={overrides.reveal}
                cascade={true}
                className={classNames("__wab_instance", sty.reveal)}
                direction={"up" as const}
                effect={"slide" as const}
                triggerOnce={true}
              >
                <div
                  data-plasmic-name={"freeBox"}
                  data-plasmic-override={overrides.freeBox}
                  className={classNames(projectcss.all, sty.freeBox)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kzq5
                    )}
                  >
                    {"check out my music!"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xWogX
                    )}
                  >
                    {
                      "i produce electronic music and also dj! i like making music with high energy and cute sounds! my main genes range from kawaii future bass to hardcore (and more). my inspirations include kawaii future bass producers like snail's house, hardcore producers like camellia, and rhythm game producers like tanger. i hope you enjoy listening to my music! "
                    }
                  </div>
                </div>
              </Reveal>

              <MusicSlides
                data-plasmic-name={"musicSlides"}
                data-plasmic-override={overrides.musicSlides}
                className={classNames("__wab_instance", sty.musicSlides)}
              />

              <Footer
                data-plasmic-name={"footer"}
                data-plasmic-override={overrides.footer}
                className={classNames("__wab_instance", sty.footer)}
              />
            </p.Stack>
          </div>
        ) : null}
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "main",
    "reveal",
    "freeBox",
    "musicSlides",
    "footer"
  ],
  navbar: ["navbar"],
  main: ["main", "reveal", "freeBox", "musicSlides", "footer"],
  reveal: ["reveal", "freeBox"],
  freeBox: ["freeBox"],
  musicSlides: ["musicSlides"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  main: "div";
  reveal: typeof Reveal;
  freeBox: "div";
  musicSlides: typeof MusicSlides;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMusic__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMusic__VariantsArgs;
    args?: PlasmicMusic__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMusic__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicMusic__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicMusic__ArgProps,
          internalVariantPropNames: PlasmicMusic__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicMusic__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMusic";
  } else {
    func.displayName = `PlasmicMusic.${nodeName}`;
  }
  return func;
}

export const PlasmicMusic = Object.assign(
  // Top-level PlasmicMusic renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    main: makeNodeComponent("main"),
    reveal: makeNodeComponent("reveal"),
    freeBox: makeNodeComponent("freeBox"),
    musicSlides: makeNodeComponent("musicSlides"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicMusic
    internalVariantProps: PlasmicMusic__VariantProps,
    internalArgProps: PlasmicMusic__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "disuko - music",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicMusic;
/* prettier-ignore-end */
